"""Render the README comparison figure from the pooled reference results.

The input is generated by ``baselines/build_reference.py`` from the
per-trial JSON files. Install the optional ``figures`` dependency to regenerate
the committed PNG: ``pip install -e '.[figures]'``.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt


ROOT = Path(__file__).resolve().parents[1]
POLICIES = ("cEI", "cEI-tMSE", "cKG")
DISPLAY_POLICY = {"cEI-tMSE": "cEI/tMSE alternation"}
POLICY_STYLE = {
    "cEI": ("#386cb0", "o"),
    "cEI-tMSE": ("#1b9e77", "s"),
    "cKG": ("#e66101", "^"),
}
SURFACES = (
    ("osa", "OSA"),
    ("gbump", "Gaussian bump"),
    ("efftox", "EffTox-style"),
    ("mariposa", "MARIPOSA"),
)
PANELS = (
    ("rec_true_eff", "Recommended efficacy ↑", 1.0),
    ("rec_unsafe", "Final selections above the toxicity limit (%) ↓", 100.0),
    ("dose_units", "OBD location error (grid units) ↓", 1.0),
)
GAMMAS = (0.5, 0.6, 0.7, 0.8, 0.9)


def render(reference: Path, output: Path) -> None:
    data = json.loads(reference.read_text())
    by_gamma = data["by_gamma"]
    for sim, _ in SURFACES:
        expected_n = 200 if sim in {"osa", "gbump"} else 100
        for policy in POLICIES:
            for gamma in GAMMAS:
                cell = by_gamma[sim][policy][f"{gamma:.1f}"]
                for metric, *_ in PANELS:
                    if metric not in cell:
                        raise ValueError(f"reference data are missing {sim}/{policy}/{gamma}/{metric}")
                if cell["dose_units"]["n_seeds"] != expected_n:
                    raise ValueError(
                        f"{sim}/{policy}/{gamma} has {cell['dose_units']['n_seeds']} seeds; "
                        f"expected {expected_n}"
                    )

    plt.rcParams.update({
        "font.size": 9,
        "axes.titlesize": 11,
        "axes.labelsize": 10,
        "xtick.labelsize": 8.5,
        "ytick.labelsize": 8.5,
    })
    fig, axes = plt.subplots(4, 3, figsize=(12, 10), sharex=True)

    for row, (sim, surface_label) in enumerate(SURFACES):
        for col, (metric, title, multiplier) in enumerate(PANELS):
            axis = axes[row, col]
            all_bounds = []
            for policy in POLICIES:
                color, marker = POLICY_STYLE[policy]
                means, ses = [], []
                for gamma in GAMMAS:
                    item = by_gamma[sim][policy][f"{gamma:.1f}"][metric]
                    means.append(multiplier * item["mean"])
                    ses.append(multiplier * item["se"])
                all_bounds.extend([mean - se for mean, se in zip(means, ses)])
                all_bounds.extend([mean + se for mean, se in zip(means, ses)])
                axis.errorbar(
                    GAMMAS,
                    means,
                    yerr=ses,
                    label=DISPLAY_POLICY.get(policy, policy),
                    color=color,
                    marker=marker,
                    markersize=4.8,
                    markeredgecolor="white",
                    markeredgewidth=0.6,
                    linewidth=1.7,
                    elinewidth=1,
                    capsize=2,
                )

            low, high = min(all_bounds), max(all_bounds)
            padding = max((high - low) * 0.14, 1e-8)
            axis.set_ylim(low - padding, high + padding)
            axis.set_xlim(0.48, 0.92)
            axis.set_xticks(GAMMAS)
            axis.grid(color="#e1e1e1", linewidth=0.7)
            axis.set_axisbelow(True)
            axis.spines[["top", "right"]].set_visible(False)
            if row == 0:
                axis.set_title(title, fontweight="semibold", pad=9)
            if col == 0:
                axis.set_ylabel(surface_label, fontweight="semibold", labelpad=10)
            if row == len(SURFACES) - 1:
                axis.set_xlabel("Toxicity-rule stringency τ (larger is stricter)")

    handles, labels = axes[0, 0].get_legend_handles_labels()
    fig.legend(
        handles,
        labels,
        loc="upper center",
        bbox_to_anchor=(0.74, 0.948),
        ncol=3,
        frameon=False,
        handlelength=2.2,
        columnspacing=1.6,
    )
    fig.suptitle("Policy comparisons across four simulation surfaces", x=0.07, ha="left", fontsize=16, fontweight="semibold")
    fig.text(
        0.07,
        0.94,
        "Means ± 1 seed-clustered Monte Carlo SE; strata averaged within seed",
        color="#555555",
        fontsize=10,
    )
    fig.text(
        0.99,
        0.012,
        "Exact formal cKG · strict stable-z latent gate · fixed calibrated noise · budget 40 · 4 warm-up observations · cohort size 2 · 5×5 grid",
        ha="right",
        fontsize=8.2,
        color="#666666",
    )
    fig.tight_layout(rect=(0.055, 0.04, 1, 0.91), h_pad=2.0, w_pad=2.2)
    output.parent.mkdir(parents=True, exist_ok=True)
    source_hashes = ", ".join(
        f"{name}:{meta['uncompressed_sha256']}"
        for name, meta in sorted(data["_source_files"].items())
    )
    fig.savefig(
        output,
        dpi=180,
        bbox_inches="tight",
        facecolor="white",
        metadata={
            "Title": "Policy comparisons across four combination-dose surfaces",
            "Description": "Generated from the source result files: " + source_hashes,
        },
    )
    plt.close(fig)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--reference", type=Path, default=ROOT / "baselines/reference_numbers.json")
    parser.add_argument("--output", type=Path, default=ROOT / "docs/decision_tradeoffs.png")
    args = parser.parse_args()
    render(args.reference, args.output)
    print(f"wrote {args.output}")


if __name__ == "__main__":
    main()
