#!/usr/bin/env python3
"""Independent path core for the frozen budget/toxicity-calibration audit.

The audit deliberately does not edit :mod:`dose_combination_bo.trial`.  Instead, one
process-local call temporarily injects a fixed-noise fitting shim and an audited
``Context`` constructor into the already frozen trial harness.  The shim changes
only the toxicity likelihood variance used for fitting; observations continue to
be generated by the frozen harness at the OSA truth noise.  Every injected global
is restored in ``finally``.

One maximum-budget path is generated and its shorter terminal states are replayed
from exact allocation/observation prefixes.  The replay serializes enough
posterior state that downstream analysis never needs to refit a GP.
"""
from __future__ import annotations

from contextlib import contextmanager, nullcontext
from decimal import Decimal, localcontext
import hashlib
import math
from typing import Any, Iterator, Mapping, Sequence

import numpy as np
import scipy.stats as ss
import torch

import dose_combination_bo.ckg_exact as exact_module
import dose_combination_bo.trial as trial_module
from dose_combination_bo.ckg_exact import ckg_scores_exact
from dose_combination_bo.context import Context as _BaseContext
from dose_combination_bo.gp import fit_gp as _base_fit_gp
from dose_combination_bo.gp import post_latent
from dose_combination_bo.metrics import dose_units
from dose_combination_bo.registry import ACQUISITIONS
from dose_combination_bo.surfaces import resolve_surface


SCHEMA_VERSION = 1
PATH_SCHEMA_VERSION = SCHEMA_VERSION
DESIGN_ID = "budget_toxicity_calibration_v1"
EXACT_POLICY = "cKG-exact-formal"
POLICIES = (EXACT_POLICY, "tmse", "qBIG", "cEI")
PRODUCTION_FACTORS = (0.5, 1.0, 2.0)
PRODUCTION_GAMMAS = (0.7, 0.9)
PRODUCTION_SNAPSHOT_BUDGETS = (20, 40, 80)
PATH_SORT_FIELDS = (
    "seed",
    "stratum",
    "gamma",
    "policy",
    "assumed_tox_noise_sd_factor",
)
GRID_N = 5
WARMUP = 4
COHORT_SIZE = 2

_FROZEN_RUN_TRIAL = trial_module.run_trial
_FROZEN_TRIAL_FIT_GP = trial_module.fit_gp
_FROZEN_TRIAL_CONTEXT = trial_module.Context
_FROZEN_NORMAL_INTERVAL_PROBABILITY = exact_module._normal_interval_probability
_FROZEN_LOG_NORMAL_INTERVAL_PROBABILITY = (
    exact_module._log_normal_interval_probability
)
_MISSING = object()
_ACTIVE_CAPTURE: dict[str, Any] | None = None
_ACTIVE_INTERVAL_AUDIT: dict[str, Any] | None = None
_WORKER_PREVIOUS_EXACT: object = _MISSING
_WORKER_INITIALIZED = False

# Two analytically distinct gate thresholds can be only a handful of binary64
# values apart.  Subtracting their CDFs is then ill-conditioned even when the
# interval lies near the centre of the normal distribution.  The calibration
# audit alone uses a certified midpoint integral for those machine-colliding
# intervals; the frozen exact-cKG implementation remains byte-for-byte unchanged.
_NARROW_INTERVAL_MAX_ULPS = 64.0
_NARROW_INTERVAL_MAX_ABS_MIDPOINT = Decimal("50")
_NARROW_INTERVAL_ANALYTIC_LOG_ERROR_CAP = Decimal.from_float(1e-12)
_NARROW_INTERVAL_DECIMAL_PRECISION = 80
_DECIMAL_LOG_SQRT_2PI = Decimal(
    "0.9189385332046727417803297364056176398613974736377834128171515404827656959272603976947432986359541976220056466246343"
)

_INTERVAL_AUDIT_PROBABILITY_COUNT = (
    "narrow_interval_probability_fallback_count"
)
_INTERVAL_AUDIT_LOG_PROBABILITY_COUNT = (
    "narrow_interval_log_probability_fallback_count"
)
_INTERVAL_AUDIT_MAX_BOUND = (
    "narrow_interval_fallback_max_analytic_log_error_bound"
)
_INTERVAL_AUDIT_CAP = "narrow_interval_fallback_analytic_log_error_cap"
_INTERVAL_AUDIT_PAIR_CHECK = (
    "narrow_interval_fallback_pair_count_identity_checked"
)


class CalibrationCoreError(RuntimeError):
    """Raised when a construction, injection, or replay invariant fails."""


def _decimal_upper_float(value: Decimal) -> float:
    """Round a non-negative Decimal upward to a conservative binary64 bound."""
    out = float(value)
    if Decimal.from_float(out) < value:
        out = math.nextafter(out, math.inf)
    return out


def _narrow_interval_midpoint_approximation(
    lo: float, hi: float
) -> tuple[float, float, float] | None:
    """Return a certified ``(probability, log_probability, delta)`` if narrow.

    Let ``w = hi - lo`` and ``m = (lo + hi) / 2``.  For ``x = m + u`` in the
    interval,

    ``abs(log(phi(x)) - log(phi(m))) <= abs(m) * w / 2 + w**2 / 8 = delta``.

    Consequently ``w * phi(m)`` has absolute log error at most ``delta`` and
    relative probability error at most ``expm1(delta)``.  Decimal arithmetic is
    used only after the binary64 geometry meets the frozen, outcome-independent
    trigger below.  The returned floats add at most their final conversion
    rounding to that analytic approximation bound.
    """
    lo = float(lo)
    hi = float(hi)
    if not (math.isfinite(lo) and math.isfinite(hi) and lo < hi):
        return None
    width_float = hi - lo
    if not math.isfinite(width_float) or width_float <= 0.0:
        return None
    ulp_scale = max(math.ulp(lo), math.ulp(hi))
    if width_float > _NARROW_INTERVAL_MAX_ULPS * ulp_scale:
        return None

    with localcontext() as decimal_context:
        decimal_context.prec = _NARROW_INTERVAL_DECIMAL_PRECISION
        decimal_lo = Decimal.from_float(lo)
        decimal_hi = Decimal.from_float(hi)
        width = decimal_hi - decimal_lo
        midpoint = decimal_lo + width / 2
        delta = abs(midpoint) * width / 2 + width * width / 8
        if (
            abs(midpoint) > _NARROW_INTERVAL_MAX_ABS_MIDPOINT
            or delta > _NARROW_INTERVAL_ANALYTIC_LOG_ERROR_CAP
        ):
            return None
        log_probability = (
            width.ln()
            - midpoint * midpoint / 2
            - _DECIMAL_LOG_SQRT_2PI
        )
        probability = log_probability.exp()
    probability_float = float(probability)
    # Eligibility is paired: the ordinary and log helpers must both receive a
    # representable result.  Deep-tail midpoint mass that converts to zero (or a
    # nonfinite value) is delegated to the frozen backend without clamping.
    if not math.isfinite(probability_float) or probability_float <= 0.0:
        return None
    return (
        probability_float,
        float(log_probability),
        _decimal_upper_float(delta),
    )


def _record_interval_fallback(kind: str, delta: float) -> None:
    audit = _ACTIVE_INTERVAL_AUDIT
    if audit is None:
        raise CalibrationCoreError(
            "narrow-interval fallback was invoked outside its calibration context"
        )
    if kind == "probability":
        key = _INTERVAL_AUDIT_PROBABILITY_COUNT
    elif kind == "log_probability":
        key = _INTERVAL_AUDIT_LOG_PROBABILITY_COUNT
    else:  # pragma: no cover - only the two private wrappers call this helper.
        raise CalibrationCoreError(f"unknown interval-fallback audit kind {kind!r}")
    audit[key] = int(audit[key]) + 1
    audit[_INTERVAL_AUDIT_MAX_BOUND] = max(
        float(audit[_INTERVAL_AUDIT_MAX_BOUND]), float(delta)
    )


def _calibration_normal_interval_probability(lo: float, hi: float) -> float:
    approximation = _narrow_interval_midpoint_approximation(lo, hi)
    if approximation is None:
        return float(_FROZEN_NORMAL_INTERVAL_PROBABILITY(lo, hi))
    probability, _log_probability, delta = approximation
    _record_interval_fallback("probability", delta)
    return probability


def _calibration_log_normal_interval_probability(lo: float, hi: float) -> float:
    approximation = _narrow_interval_midpoint_approximation(lo, hi)
    if approximation is None:
        return float(_FROZEN_LOG_NORMAL_INTERVAL_PROBABILITY(lo, hi))
    _probability, log_probability, delta = approximation
    _record_interval_fallback("log_probability", delta)
    return log_probability


def _new_interval_audit() -> dict[str, Any]:
    return {
        _INTERVAL_AUDIT_PROBABILITY_COUNT: 0,
        _INTERVAL_AUDIT_LOG_PROBABILITY_COUNT: 0,
        _INTERVAL_AUDIT_MAX_BOUND: 0.0,
        _INTERVAL_AUDIT_CAP: _decimal_upper_float(
            _NARROW_INTERVAL_ANALYTIC_LOG_ERROR_CAP
        ),
        _INTERVAL_AUDIT_PAIR_CHECK: False,
    }


@contextmanager
def _temporary_calibration_interval_backend(
    audit: dict[str, Any],
) -> Iterator[None]:
    """Install the paired narrow-interval backend and invariably restore it."""
    global _ACTIVE_INTERVAL_AUDIT
    if _ACTIVE_INTERVAL_AUDIT is not None:
        raise CalibrationCoreError("nested calibration interval backends are prohibited")
    if exact_module._normal_interval_probability is not _FROZEN_NORMAL_INTERVAL_PROBABILITY:
        raise CalibrationCoreError(
            "ordinary normal-interval helper is already monkey-patched"
        )
    if (
        exact_module._log_normal_interval_probability
        is not _FROZEN_LOG_NORMAL_INTERVAL_PROBABILITY
    ):
        raise CalibrationCoreError(
            "log normal-interval helper is already monkey-patched"
        )
    expected = _new_interval_audit()
    if audit != expected:
        raise CalibrationCoreError(
            "calibration interval audit must start from the canonical zero state"
        )
    original_probability = _FROZEN_NORMAL_INTERVAL_PROBABILITY
    original_log_probability = _FROZEN_LOG_NORMAL_INTERVAL_PROBABILITY
    _ACTIVE_INTERVAL_AUDIT = audit
    exact_module._normal_interval_probability = (  # type: ignore[assignment]
        _calibration_normal_interval_probability
    )
    exact_module._log_normal_interval_probability = (  # type: ignore[assignment]
        _calibration_log_normal_interval_probability
    )
    try:
        yield
    finally:
        backend_tampered = (
            exact_module._normal_interval_probability
            is not _calibration_normal_interval_probability
            or exact_module._log_normal_interval_probability
            is not _calibration_log_normal_interval_probability
        )
        exact_module._normal_interval_probability = original_probability  # type: ignore[assignment]
        exact_module._log_normal_interval_probability = original_log_probability  # type: ignore[assignment]
        _ACTIVE_INTERVAL_AUDIT = None
        if backend_tampered:
            raise CalibrationCoreError(
                "calibration interval backend changed while active; originals restored"
            )


def _exact_scores(ctx: _BaseContext) -> np.ndarray:
    """The private, deterministic finite-panel exact cKG evaluator."""
    return np.asarray(ckg_scores_exact(ctx), dtype=float)


_exact_scores.acquisition_name = EXACT_POLICY  # type: ignore[attr-defined]


def initialize_worker() -> None:
    """Configure a serial worker and register exact cKG under its audit-only name.

    This function has no effect on the production ``cKG`` registry entry.  It is
    idempotent for a worker already initialized by this module.
    """
    global _WORKER_INITIALIZED, _WORKER_PREVIOUS_EXACT
    torch.set_num_threads(1)
    try:
        torch.set_num_interop_threads(1)
    except RuntimeError:
        pass
    existing = ACQUISITIONS.get(EXACT_POLICY, _MISSING)
    if existing not in {_MISSING, _exact_scores}:
        raise CalibrationCoreError(
            f"audit-only exact policy name {EXACT_POLICY!r} is already registered"
        )
    if not _WORKER_INITIALIZED:
        _WORKER_PREVIOUS_EXACT = existing
        _WORKER_INITIALIZED = True
    ACQUISITIONS[EXACT_POLICY] = _exact_scores


def cleanup_worker() -> None:
    """Undo :func:`initialize_worker` and clear any abandoned capture state."""
    global _ACTIVE_CAPTURE, _ACTIVE_INTERVAL_AUDIT
    global _WORKER_INITIALIZED, _WORKER_PREVIOUS_EXACT
    if trial_module.fit_gp is not _FROZEN_TRIAL_FIT_GP:
        trial_module.fit_gp = _FROZEN_TRIAL_FIT_GP  # type: ignore[assignment]
    if trial_module.Context is not _FROZEN_TRIAL_CONTEXT:
        trial_module.Context = _FROZEN_TRIAL_CONTEXT  # type: ignore[assignment]
    if (
        exact_module._normal_interval_probability
        is _calibration_normal_interval_probability
    ):
        exact_module._normal_interval_probability = (  # type: ignore[assignment]
            _FROZEN_NORMAL_INTERVAL_PROBABILITY
        )
    if (
        exact_module._log_normal_interval_probability
        is _calibration_log_normal_interval_probability
    ):
        exact_module._log_normal_interval_probability = (  # type: ignore[assignment]
            _FROZEN_LOG_NORMAL_INTERVAL_PROBABILITY
        )
    _ACTIVE_CAPTURE = None
    _ACTIVE_INTERVAL_AUDIT = None
    if _WORKER_INITIALIZED:
        if _WORKER_PREVIOUS_EXACT is _MISSING:
            ACQUISITIONS.pop(EXACT_POLICY, None)
        elif _WORKER_PREVIOUS_EXACT is _exact_scores:
            ACQUISITIONS[EXACT_POLICY] = _exact_scores
        else:
            # This branch is unreachable because initialize_worker rejects a
            # conflicting registration, but retaining it makes cleanup total.
            ACQUISITIONS[EXACT_POLICY] = _WORKER_PREVIOUS_EXACT  # type: ignore[assignment]
        _WORKER_PREVIOUS_EXACT = _MISSING
        _WORKER_INITIALIZED = False


@contextmanager
def _temporary_exact_registration() -> Iterator[None]:
    existing = ACQUISITIONS.get(EXACT_POLICY, _MISSING)
    if existing not in {_MISSING, _exact_scores}:
        raise CalibrationCoreError(
            f"audit-only exact policy name {EXACT_POLICY!r} conflicts with another callable"
        )
    inserted = existing is _MISSING
    if inserted:
        ACQUISITIONS[EXACT_POLICY] = _exact_scores
    try:
        yield
    finally:
        if inserted and ACQUISITIONS.get(EXACT_POLICY) is _exact_scores:
            ACQUISITIONS.pop(EXACT_POLICY, None)


def _as_float_list(value: Any) -> list[float]:
    out = np.asarray(value, dtype=float).reshape(-1)
    if not np.isfinite(out).all():
        raise CalibrationCoreError("posterior serialization encountered a nonfinite value")
    return out.tolist()


def _panel_truth(surface: Mapping[str, Any], Xset: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    efficacy = np.asarray(
        [surface["eff"](float(d[0]), float(d[1])) for d in Xset], dtype=float
    )
    toxicity = np.asarray(
        [surface["tox"](float(d[0]), float(d[1])) for d in Xset], dtype=float
    )
    return efficacy, toxicity


def _true_panel_target(
    surface: Mapping[str, Any], Xset: np.ndarray, stratum: int
) -> dict[str, Any]:
    efficacy, toxicity = _panel_truth(surface, Xset)
    feasible = toxicity <= float(surface["gd"])
    if not feasible.any():
        raise CalibrationCoreError("OSA panel unexpectedly has no truly feasible dose")
    candidates = np.flatnonzero(feasible)
    index = int(candidates[int(np.argmax(efficacy[candidates]))])
    expected = {
        0: (8, (0.25, 0.75), 7.67921875, 1.2816796875, 11),
        1: (13, (0.50, 0.75), 13.20546875, 1.6223437500000002, 16),
    }[int(stratum)]
    if index != expected[0]:
        raise CalibrationCoreError(
            f"recomputed true panel target index {index} differs from frozen {expected[0]}"
        )
    observed = (tuple(Xset[index]), efficacy[index], toxicity[index], int(feasible.sum()))
    if not np.allclose(observed[0], expected[1], rtol=0.0, atol=1e-14):
        raise CalibrationCoreError("recomputed true panel target dose differs from frozen design")
    if not np.isclose(observed[1], expected[2], rtol=0.0, atol=1e-12):
        raise CalibrationCoreError("recomputed true panel target efficacy differs from frozen design")
    if not np.isclose(observed[2], expected[3], rtol=0.0, atol=1e-12):
        raise CalibrationCoreError("recomputed true panel target toxicity differs from frozen design")
    if observed[3] != expected[4]:
        raise CalibrationCoreError("recomputed true feasible-dose count differs from frozen design")
    return {
        "canonical_index": index,
        "dose": Xset[index].astype(float).tolist(),
        "true_efficacy": float(efficacy[index]),
        "true_toxicity": float(toxicity[index]),
        "toxicity_threshold": float(surface["gd"]),
        "true_feasible_dose_count": int(feasible.sum()),
    }


def _gp_parameters(model: Any, likelihood: Any) -> dict[str, Any]:
    return {
        "mean_constant": float(model.mean_module.constant.detach().cpu().reshape(-1)[0]),
        "outputscale": float(model.covar_module.outputscale.detach().cpu().reshape(-1)[0]),
        "lengthscales": _as_float_list(
            model.covar_module.base_kernel.lengthscale.detach().cpu()
        ),
        "observation_noise_variance": float(likelihood.noise.detach().cpu().reshape(-1)[0]),
    }


def _capture_checkpoint(ctx: _BaseContext, capture: dict[str, Any]) -> None:
    latest = capture.get("latest_pair")
    if not isinstance(latest, Mapping):
        raise CalibrationCoreError("Context was constructed before a complete fit pair")
    n = int(latest["n"])
    if (
        ctx.me is not latest["me"]
        or ctx.le is not latest["le"]
        or ctx.mt is not latest["mt"]
        or ctx.lt is not latest["lt"]
    ):
        raise CalibrationCoreError(
            "Context did not receive the most recent fitted model/likelihood pair"
        )
    if capture["checkpoints"] and n <= int(capture["checkpoints"][-1]["n"]):
        raise CalibrationCoreError("posterior checkpoint enrollment is not strictly increasing")
    target_index = int(capture["target_index"])
    mu = float(ctx.mu_g[target_index])
    sd = float(ctx.sd_g[target_index])
    stable_z = float(ctx.standardized_feasibility[target_index])
    expected_z = (float(ctx.g_dagger) - mu) / sd
    expected_mask = np.asarray(ctx.standardized_feasibility) > float(ctx.gate_quantile)
    if not np.isclose(stable_z, expected_z, rtol=1e-12, atol=1e-12):
        raise CalibrationCoreError("Context target stable-z value failed independent replay")
    if not np.array_equal(expected_mask, np.asarray(ctx.gate_safe, dtype=bool)):
        raise CalibrationCoreError("Context gate mask failed strict stable-z replay")
    item = {
        "n": n,
        "target_toxicity_mean": mu,
        "target_toxicity_latent_sd": sd,
        "target_stable_z": stable_z,
        "target_feasibility_probability": float(ss.norm.cdf(stable_z)),
        "target_admitted": bool(ctx.gate_safe[target_index]),
        "gate_count": int(np.sum(ctx.gate_safe)),
        "gate_empty": not bool(np.any(ctx.gate_safe)),
        "most_feasible_index": int(ctx.most_feasible_full_index),
        "fitted_toxicity_noise_variance": float(ctx.lt.noise.item()),
    }
    capture["checkpoints"].append(item)
    capture["context_count"] += 1
    if n in capture["snapshot_budgets"]:
        mu_f, var_f = post_latent(ctx.me, ctx.Xset)
        capture["context_snapshots"][n] = {
            "efficacy_mean": _as_float_list(mu_f.cpu().numpy()),
            "efficacy_sd": _as_float_list(var_f.clamp_min(1e-12).sqrt().cpu().numpy()),
            "toxicity_mean": _as_float_list(ctx.mu_g),
            "toxicity_sd": _as_float_list(ctx.sd_g),
            "toxicity_stable_z": _as_float_list(ctx.standardized_feasibility),
            "toxicity_feasibility_probability": _as_float_list(ctx.pf),
            "gate_mask": np.asarray(ctx.gate_safe, dtype=bool).tolist(),
        }


def _capturing_context(*args: Any, **kwargs: Any) -> _BaseContext:
    if _ACTIVE_CAPTURE is None:
        raise CalibrationCoreError("calibration Context constructed outside an active path")
    ctx = _BaseContext(*args, **kwargs)
    _capture_checkpoint(ctx, _ACTIVE_CAPTURE)
    return ctx


def _calibrated_fit_gp(
    X: torch.Tensor,
    y: torch.Tensor,
    noise_cap: float = 0.3,
    iters: int = 120,
    lr: float = 0.1,
    fixed_noise: float | None = None,
):
    """Alternating endpoint shim used only while the frozen harness is active."""
    capture = _ACTIVE_CAPTURE
    if capture is None:
        raise CalibrationCoreError("calibrated fit shim called outside an active path")
    phase = capture["fit_call_count"] % 2
    capture["fit_call_count"] += 1
    n = int(X.shape[0])
    x_np = np.asarray(X.detach().cpu(), dtype=float)
    y_np = np.asarray(y.detach().cpu(), dtype=float).reshape(-1)
    if x_np.shape != (n, 2) or y_np.shape != (n,):
        raise CalibrationCoreError("frozen fit call has an unexpected training-data shape")
    if phase == 0:
        expected = float(capture["truth_eff_noise_variance"])
        if fixed_noise is None or not np.isclose(float(fixed_noise), expected, rtol=0.0, atol=1e-12):
            raise CalibrationCoreError("frozen efficacy fit did not carry the true fixed variance")
        model, likelihood = _base_fit_gp(
            X, y, noise_cap=noise_cap, iters=iters, lr=lr, fixed_noise=expected
        )
        capture["pending_pair"] = {
            "n": n,
            "X": x_np.copy(),
            "Yf": y_np.copy(),
            "me": model,
            "le": likelihood,
        }
        return model, likelihood

    pending = capture.get("pending_pair")
    if not isinstance(pending, dict) or int(pending["n"]) != n:
        raise CalibrationCoreError("toxicity fit was not paired with its efficacy fit")
    if not np.array_equal(np.asarray(pending["X"]), x_np):
        raise CalibrationCoreError("efficacy and toxicity fits used different allocations")
    expected_truth = float(capture["truth_tox_noise_variance"])
    if fixed_noise is None or not np.isclose(
        float(fixed_noise), expected_truth, rtol=0.0, atol=1e-12
    ):
        raise CalibrationCoreError("frozen toxicity fit did not carry the true fixed variance")
    assumed = float(capture["assumed_tox_noise_variance"])
    model, likelihood = _base_fit_gp(
        X, y, noise_cap=noise_cap, iters=iters, lr=lr, fixed_noise=assumed
    )
    pending.update({"Yg": y_np.copy(), "mt": model, "lt": likelihood})
    capture["latest_pair"] = pending
    capture["pending_pair"] = None
    capture["fit_pair_count"] += 1
    return model, likelihood


@contextmanager
def _temporary_trial_injection(capture: dict[str, Any]) -> Iterator[None]:
    """Install and invariably restore the two frozen-harness shims."""
    global _ACTIVE_CAPTURE
    if _ACTIVE_CAPTURE is not None:
        raise CalibrationCoreError("nested or concurrent calibration paths are prohibited")
    if trial_module.fit_gp is not _FROZEN_TRIAL_FIT_GP:
        raise CalibrationCoreError("dose_combination_bo.trial.fit_gp is already monkey-patched")
    if trial_module.Context is not _FROZEN_TRIAL_CONTEXT:
        raise CalibrationCoreError("dose_combination_bo.trial.Context is already monkey-patched")
    _ACTIVE_CAPTURE = capture
    trial_module.fit_gp = _calibrated_fit_gp  # type: ignore[assignment]
    trial_module.Context = _capturing_context  # type: ignore[assignment]
    try:
        yield
    finally:
        trial_module.fit_gp = _FROZEN_TRIAL_FIT_GP  # type: ignore[assignment]
        trial_module.Context = _FROZEN_TRIAL_CONTEXT  # type: ignore[assignment]
        _ACTIVE_CAPTURE = None


def _posterior_state(
    history: np.ndarray,
    observed_efficacy: np.ndarray,
    observed_toxicity: np.ndarray,
    budget: int,
    Xset_t: torch.Tensor,
    surface: Mapping[str, Any],
    gamma: float,
    assumed_tox_noise_variance: float,
) -> tuple[dict[str, Any], Any, Any, Any, Any]:
    observed = torch.tensor(history[:budget], dtype=torch.double)
    me, le = _base_fit_gp(
        observed,
        torch.tensor(observed_efficacy[:budget], dtype=torch.double),
        fixed_noise=float(surface["sf"]) ** 2,
    )
    mt, lt = _base_fit_gp(
        observed,
        torch.tensor(observed_toxicity[:budget], dtype=torch.double),
        fixed_noise=float(assumed_tox_noise_variance),
    )
    mu_f_t, var_f_t = post_latent(me, Xset_t)
    mu_g_t, var_g_t = post_latent(mt, Xset_t)
    mu_f = np.asarray(mu_f_t.cpu(), dtype=float)
    sd_f = np.asarray(var_f_t.clamp_min(1e-12).sqrt().cpu(), dtype=float)
    mu_g = np.asarray(mu_g_t.cpu(), dtype=float)
    sd_g = np.asarray(var_g_t.clamp_min(1e-12).sqrt().cpu(), dtype=float)
    stable_z = (float(surface["gd"]) - mu_g) / sd_g
    pf = ss.norm.cdf(stable_z)
    quantile = float(ss.norm.ppf(float(gamma)))
    gate = stable_z > quantile
    rec_index = int(np.argmax(np.where(gate, mu_f, -np.inf))) if gate.any() else int(np.argmax(stable_z))
    return (
        {
            "budget": int(budget),
            "n_enrolled": int(budget),
            "efficacy_posterior_mean": _as_float_list(mu_f),
            "efficacy_posterior_latent_sd": _as_float_list(sd_f),
            "toxicity_posterior_mean": _as_float_list(mu_g),
            "toxicity_posterior_latent_sd": _as_float_list(sd_g),
            "toxicity_stable_z": _as_float_list(stable_z),
            "toxicity_feasibility_probability": _as_float_list(pf),
            "gate_mask": gate.astype(bool).tolist(),
            "gate_quantile": quantile,
            "fitted_efficacy_gp": _gp_parameters(me, le),
            "fitted_toxicity_gp": _gp_parameters(mt, lt),
            "independent_recommendation_index": rec_index,
        },
        me,
        le,
        mt,
        lt,
    )


def _terminal_index_from_result(result: Mapping[str, Any], Xset: np.ndarray) -> int:
    saved = np.asarray([result["rec_d1"], result["rec_d2"]], dtype=float)
    matches = np.flatnonzero(np.all(Xset == saved[None, :], axis=1))
    if len(matches) != 1:
        raise CalibrationCoreError("frozen harness terminal recommendation is not one panel dose")
    return int(matches[0])


def _replay_outcome_innovations(
    seed: int,
    maximum_budget: int,
    history: np.ndarray,
    observed_efficacy: np.ndarray,
    observed_toxicity: np.ndarray,
    surface: Mapping[str, Any],
) -> dict[str, Any]:
    """Replay and hash the allocation-independent ordered Gaussian innovations."""
    rng = np.random.default_rng(int(seed))
    z_eff: list[float] = []
    z_tox: list[float] = []
    cut = np.linspace(0.0, 1.0, WARMUP + 1)
    for index in range(int(maximum_budget)):
        if index < WARMUP:
            expected = np.asarray(
                [
                    cut[index] + rng.uniform() * (cut[1] - cut[0]),
                    rng.uniform(),
                ],
                dtype=float,
            )
            if not np.array_equal(expected, history[index]):
                raise CalibrationCoreError("innovation replay failed the frozen LHS warm-up")
        z_eff.append(float(rng.standard_normal()))
        z_tox.append(float(rng.standard_normal()))
    z_eff_array = np.asarray(z_eff, dtype="<f8")
    z_tox_array = np.asarray(z_tox, dtype="<f8")
    expected_eff = np.asarray(
        [surface["eff"](float(d[0]), float(d[1])) for d in history], dtype=float
    ) + float(surface["sf"]) * z_eff_array
    expected_tox = np.asarray(
        [surface["tox"](float(d[0]), float(d[1])) for d in history], dtype=float
    ) + float(surface["sg"]) * z_tox_array
    if not np.allclose(expected_eff, observed_efficacy, rtol=0.0, atol=2e-14):
        raise CalibrationCoreError("efficacy observations failed innovation-stream replay")
    if not np.allclose(expected_tox, observed_toxicity, rtol=0.0, atol=2e-14):
        raise CalibrationCoreError("toxicity observations failed innovation-stream replay")
    combined = np.column_stack([z_eff_array, z_tox_array]).astype("<f8", copy=False)
    return {
        "algorithm": "sha256_little_endian_float64_interleaved_z_eff_z_tox",
        "combined_sha256": hashlib.sha256(combined.tobytes(order="C")).hexdigest(),
        "efficacy_sha256": hashlib.sha256(z_eff_array.tobytes(order="C")).hexdigest(),
        "toxicity_sha256": hashlib.sha256(z_tox_array.tobytes(order="C")).hexdigest(),
        "innovation_count_per_endpoint": int(maximum_budget),
        "observation_replay_max_abs_error": float(
            max(
                np.max(np.abs(expected_eff - observed_efficacy)),
                np.max(np.abs(expected_tox - observed_toxicity)),
            )
        ),
    }


def _legacy_recs(
    mu_f: np.ndarray,
    stable_z: np.ndarray,
    Xset: np.ndarray,
    true_eff: np.ndarray,
    true_tox: np.ndarray,
    surface: Mapping[str, Any],
) -> list[dict[str, Any]]:
    output: list[dict[str, Any]] = []
    for gamma in (0.5, 0.6, 0.7, 0.8, 0.9, 0.95):
        gate = stable_z > float(ss.norm.ppf(gamma))
        idx = int(np.argmax(np.where(gate, mu_f, -np.inf))) if gate.any() else int(np.argmax(stable_z))
        output.append(
            {
                "grec": float(gamma),
                "du": float(dose_units(Xset[idx], surface["dopt"], spacing=0.25)),
                "unsafe": int(true_tox[idx] > float(surface["gd"])),
                "eff_reg": float(float(surface["fopt"]) - true_eff[idx]),
            }
        )
    return output


def _legacy_singleton_metrics(
    *,
    efficacy_model: Any,
    toxicity_model: Any,
    rec_index: int,
    Xset_t: torch.Tensor,
    surface: Mapping[str, Any],
) -> dict[str, float]:
    """Replay the frozen harness's singleton terminal-posterior readouts.

    The 25-dose posterior vectors remain the scientific state used for gates and
    decisions.  These three legacy serialization fields instead have to preserve
    the exact query shapes and formulas in ``dose_combination_bo.trial.run_trial``:
    efficacy at the recommended dose first, then toxicity at the panel dose
    nearest the stored OBD reference.  A component of a batched 25-dose solve can
    differ from the corresponding singleton solve in the last binary64 bits.
    """
    rec = Xset_t[int(rec_index)]
    muf_rec, varf_rec = post_latent(
        efficacy_model,
        torch.tensor(np.array([rec]), dtype=torch.double),
    )
    rpsel = float(
        np.sqrt(
            (float(muf_rec.reshape(-1)[0]) - float(surface["fopt"])) ** 2
            + float(varf_rec.reshape(-1)[0])
        )
    )

    nearest_obd = int(
        np.argmin(
            np.linalg.norm(
                np.asarray(Xset_t.cpu(), dtype=float)
                - np.asarray(surface["dopt"], dtype=float),
                axis=1,
            )
        )
    )
    mu_go, vgo = post_latent(
        toxicity_model,
        Xset_t[nearest_obd : nearest_obd + 1],
    )
    sdo = float(vgo.clamp_min(1e-12).sqrt().reshape(-1)[0])
    obd_pf = float(
        ss.norm.cdf(
            (float(surface["gd"]) - float(mu_go.reshape(-1)[0])) / sdo
        )
    )
    return {"rpsel": rpsel, "obd_pf": obd_pf, "obd_sdg": sdo}


def _finalize_snapshot(
    state: dict[str, Any],
    *,
    record_identity: Mapping[str, Any],
    surface: Mapping[str, Any],
    Xset: np.ndarray,
    true_eff: np.ndarray,
    true_tox: np.ndarray,
    target: Mapping[str, Any],
    history: np.ndarray,
    above: np.ndarray,
    checkpoints: Sequence[Mapping[str, Any]],
    context_state: Mapping[str, Any] | None,
    harness_result: Mapping[str, Any],
    efficacy_model: Any,
    toxicity_model: Any,
) -> dict[str, Any]:
    budget = int(state["budget"])
    mu_f = np.asarray(state["efficacy_posterior_mean"], dtype=float)
    sd_f = np.asarray(state["efficacy_posterior_latent_sd"], dtype=float)
    mu_g = np.asarray(state["toxicity_posterior_mean"], dtype=float)
    sd_g = np.asarray(state["toxicity_posterior_latent_sd"], dtype=float)
    stable_z = np.asarray(state["toxicity_stable_z"], dtype=float)
    pf = np.asarray(state["toxicity_feasibility_probability"], dtype=float)
    gate = np.asarray(state["gate_mask"], dtype=bool)
    target_index = int(target["canonical_index"])
    rec_index = int(state.pop("independent_recommendation_index"))
    true_feasible = true_tox <= float(surface["gd"])
    selected_true_feasible = bool(true_feasible[rec_index])
    prefix_checkpoints = [dict(item) for item in checkpoints if int(item["n"]) <= budget]
    if not prefix_checkpoints or int(prefix_checkpoints[-1]["n"]) != budget:
        raise CalibrationCoreError(f"budget {budget} has no terminal target checkpoint")
    admissions = np.asarray([item["target_admitted"] for item in prefix_checkpoints], dtype=bool)
    had_preterminal_exclusion = bool((~admissions[:-1]).any()) if len(admissions) > 1 else False
    terminal_run = 0
    for admitted in admissions[::-1]:
        if admitted:
            break
        terminal_run += 1
    first = next(
        (int(item["n"]) for item in prefix_checkpoints if bool(item["target_admitted"])),
        None,
    )
    above_count = int(np.sum(above[:budget]))
    post_count = int(np.sum(above[WARMUP:budget]))
    gate_count = int(gate.sum())
    true_gate_count = int(np.sum(gate & true_feasible))
    false_admissions = int(np.sum(gate & ~true_feasible))
    target_covered = bool(
        mu_g[target_index] - 1.96 * sd_g[target_index]
        <= true_tox[target_index]
        <= mu_g[target_index] + 1.96 * sd_g[target_index]
    )
    coverage = (
        (true_tox >= mu_g - 1.96 * sd_g)
        & (true_tox <= mu_g + 1.96 * sd_g)
    )
    brier = float(np.mean((pf - true_feasible.astype(float)) ** 2))
    state["recommendation"] = {
        "index": rec_index,
        "dose": Xset[rec_index].astype(float).tolist(),
        "true_efficacy": float(true_eff[rec_index]),
        "true_toxicity": float(true_tox[rec_index]),
        "true_feasible": selected_true_feasible,
        "unsafe": not selected_true_feasible,
        "panel_correct_selection": bool(rec_index == target_index),
        "grid_unit_distance_from_target": float(
            np.linalg.norm(Xset[rec_index] - Xset[target_index]) / 0.25
        ),
        "simple_regret_if_true_feasible": (
            float(target["true_efficacy"] - true_eff[rec_index])
            if selected_true_feasible
            else None
        ),
    }
    state["target_gate"] = {
        "terminal_admitted": bool(admissions[-1]),
        "terminal_excluded": not bool(admissions[-1]),
        "ever_admitted": bool(admissions.any()),
        "never_admitted": not bool(admissions.any()),
        "admitted_then_excluded": bool(admissions[:-1].any() and not admissions[-1]),
        "admitted_finally": bool(admissions[-1]),
        "admitted_but_not_selected": bool(admissions[-1] and rec_index != target_index),
        "exclusion_occupancy": float(np.mean(~admissions)),
        "terminal_exclusion_run_fraction": float(terminal_run / len(admissions)),
        "first_admission_enrollment": first,
        "had_preterminal_exclusion": had_preterminal_exclusion,
        "recovered_after_preterminal_exclusion": bool(
            had_preterminal_exclusion and admissions[-1]
        ),
        "recovery_condition_denominator": int(had_preterminal_exclusion),
    }
    state["posterior_calibration"] = {
        "brier_score": brier,
        "latent_95_interval_coverage_proportion": float(np.mean(coverage)),
        "target_latent_95_interval_covered": target_covered,
        "mean_latent_95_interval_width": float(np.mean(2.0 * 1.96 * sd_g)),
    }
    state["gate_diagnostics"] = {
        "gate_count": gate_count,
        "gate_empty": gate_count == 0,
        "false_admissions": false_admissions,
        "true_feasible_admissions": true_gate_count,
        "feasible_dose_recall": float(true_gate_count / int(true_feasible.sum())),
        "precision_if_nonempty": (
            float(true_gate_count / gate_count) if gate_count else None
        ),
    }
    state["outcomes"] = {
        "terminal_true_boundary_exceedance_pct": float(100.0 * (not selected_true_feasible)),
        "above_boundary_assignment_count": above_count,
        "above_boundary_assignment_pct": float(100.0 * above_count / budget),
        "post_initialization_above_boundary_count": post_count,
        "post_initialization_above_boundary_pct": float(
            100.0 * post_count / (budget - WARMUP)
        ),
        "terminal_target_exclusion_pct": float(100.0 * (not admissions[-1])),
        "panel_brier_score_pct": float(100.0 * brier),
        "brier_score_pct": float(100.0 * brier),
        "panel_correct_selection_pct": float(100.0 * (rec_index == target_index)),
    }

    expected_mask = stable_z > float(state["gate_quantile"])
    if not np.array_equal(expected_mask, gate):
        raise CalibrationCoreError("terminal replay gate is not its strict stable-z mask")
    context_difference = None
    if context_state is not None:
        keys = (
            ("efficacy_mean", "efficacy_posterior_mean"),
            ("efficacy_sd", "efficacy_posterior_latent_sd"),
            ("toxicity_mean", "toxicity_posterior_mean"),
            ("toxicity_sd", "toxicity_posterior_latent_sd"),
            ("toxicity_stable_z", "toxicity_stable_z"),
            ("toxicity_feasibility_probability", "toxicity_feasibility_probability"),
        )
        context_difference = 0
        for context_key, replay_key in keys:
            if not np.allclose(
                np.asarray(context_state[context_key]),
                np.asarray(state[replay_key]),
                rtol=1e-10,
                atol=1e-10,
            ):
                context_difference += 1
        if not np.array_equal(context_state["gate_mask"], state["gate_mask"]):
            context_difference += 1
        if context_difference:
            raise CalibrationCoreError(
                f"budget {budget} independent replay differs from allocation-time Context"
            )

    harness_saved_index = None
    if budget == int(record_identity["maximum_budget"]):
        harness_saved_index = _terminal_index_from_result(harness_result, Xset)
        if harness_saved_index != rec_index:
            raise CalibrationCoreError("independent terminal rule differs from frozen harness")
    state["terminal_rule_audit"] = {
        "status": "checked",
        "stable_z_gate_difference_count": int(np.sum(expected_mask != gate)),
        "allocation_context_field_difference_count": context_difference,
        "independent_recommendation_index": rec_index,
        "harness_saved_recommendation_index": harness_saved_index,
        "recommendation_index_difference_count": (
            int(harness_saved_index != rec_index)
            if harness_saved_index is not None
            else 0
        ),
    }

    legacy_singletons = _legacy_singleton_metrics(
        efficacy_model=efficacy_model,
        toxicity_model=toxicity_model,
        rec_index=rec_index,
        Xset_t=torch.tensor(Xset, dtype=torch.double),
        surface=surface,
    )
    legacy = {
        # The authenticated selected-family oracle uses the normalized public
        # policy label even though execution uses an audit-only exact alias.
        "policy": (
            "cKG" if record_identity["policy"] == EXACT_POLICY
            else str(record_identity["policy"])
        ),
        "seed": int(record_identity["seed"]),
        "sim": "osa",
        "stratum": int(record_identity["stratum"]),
        "gamma": float(record_identity["gamma"]),
        "mode": "latent",
        "budget": budget,
        "r_k": COHORT_SIZE,
        "grid_n": GRID_N,
        "noise": "fixed",
        "kap": 1.0,
        "eff_noise_sd": float(surface["sf"]),
        "tox_noise_sd": float(surface["sg"]),
        "warmup": WARMUP,
        "empty_gate": "pf",
        "protocol_scaffold": "lhs_fixed",
        "region_step": 0.25,
        "empty_gate_stop_after": 3,
        "exclude_repeats_during_expansion": True,
        "stop_reason": None,
        "recommendation_made": True,
        "n_enrolled": budget,
        "n_unique_doses": int(len({tuple(row) for row in history[:budget]})),
        "n_empty_gate_events": int(
            sum(bool(item["gate_empty"]) for item in checkpoints if int(item["n"]) < budget)
        ),
        "initialization_patients_above": int(np.sum(above[:WARMUP])),
        "post_initialization_patients_above": post_count,
        "initialization_size": WARMUP,
        "region_q_at_stop": None,
        "allocation_history": history[:budget].astype(float).tolist(),
        "dose_units": float(dose_units(Xset[rec_index], surface["dopt"], spacing=0.25)),
        "rpsel": legacy_singletons["rpsel"],
        "rec_unsafe": int(not selected_true_feasible),
        "toxic": above_count,
        "n_gate_pass": gate_count,
        "n_gate_pass_safe": true_gate_count,
        "rec_d1": float(Xset[rec_index, 0]),
        "rec_d2": float(Xset[rec_index, 1]),
        "rec_true_eff": float(true_eff[rec_index]),
        "rec_true_tox": float(true_tox[rec_index]),
        "recs": _legacy_recs(mu_f, stable_z, Xset, true_eff, true_tox, surface),
        "obd_pf": legacy_singletons["obd_pf"],
        "obd_sdg": legacy_singletons["obd_sdg"],
        "traj": None,
    }
    state["frozen_run_trial_common"] = legacy
    return state


def _validate_inputs(
    policy: str,
    seed: int,
    z: int,
    gamma: float,
    factor: float,
    maximum_budget: int,
    snapshot_budgets: Sequence[int],
) -> tuple[int, ...]:
    if policy not in POLICIES:
        raise ValueError(f"policy must be one of {POLICIES!r}")
    if not isinstance(seed, (int, np.integer)) or int(seed) < 0:
        raise ValueError("seed must be a non-negative integer")
    if z not in {0, 1}:
        raise ValueError("z must be 0 or 1")
    if not np.isfinite(float(gamma)) or float(gamma) not in PRODUCTION_GAMMAS:
        raise ValueError(f"gamma must be one of {PRODUCTION_GAMMAS!r}")
    if not np.isfinite(float(factor)) or float(factor) not in PRODUCTION_FACTORS:
        raise ValueError(f"assumed toxicity-noise SD factor must be one of {PRODUCTION_FACTORS!r}")
    if not isinstance(maximum_budget, (int, np.integer)):
        raise ValueError("maximum_budget must be an integer")
    maximum_budget = int(maximum_budget)
    if maximum_budget < WARMUP or (maximum_budget - WARMUP) % COHORT_SIZE:
        raise ValueError("maximum_budget must be at least 4 and lie on the cohort grid")
    budgets = tuple(int(value) for value in snapshot_budgets)
    if not budgets or tuple(sorted(set(budgets))) != budgets:
        raise ValueError("snapshot_budgets must be unique and strictly increasing")
    if budgets[-1] != maximum_budget:
        raise ValueError("the last snapshot budget must equal maximum_budget")
    if any(value < WARMUP or (value - WARMUP) % COHORT_SIZE for value in budgets):
        raise ValueError("every snapshot budget must lie on the cohort grid")
    return budgets


def run_calibration_path(
    policy: str,
    seed: int,
    stratum: int,
    gamma: float,
    assumed_tox_noise_sd_factor: float,
    *,
    maximum_budget: int = 80,
    snapshot_budgets: Sequence[int] = PRODUCTION_SNAPSHOT_BUDGETS,
) -> dict[str, Any]:
    """Run one OSA path and serialize nested posterior/decision snapshots.

    Production uses ``maximum_budget=80`` and ``snapshot_budgets=(20,40,80)``.
    Smaller cohort-aligned values are accepted solely for construction tests.
    """
    budgets = _validate_inputs(
        policy,
        seed,
        stratum,
        gamma,
        assumed_tox_noise_sd_factor,
        maximum_budget,
        snapshot_budgets,
    )
    torch.set_default_dtype(torch.double)
    surface = resolve_surface("osa", int(stratum))
    Xset = trial_module.grid(GRID_N).astype(float)
    target = _true_panel_target(surface, Xset, int(stratum))
    truth_eff_variance = float(surface["sf"]) ** 2
    truth_tox_variance = float(surface["sg"]) ** 2
    factor = float(assumed_tox_noise_sd_factor)
    assumed_tox_variance = truth_tox_variance * factor**2
    capture: dict[str, Any] = {
        "truth_eff_noise_variance": truth_eff_variance,
        "truth_tox_noise_variance": truth_tox_variance,
        "assumed_tox_noise_variance": assumed_tox_variance,
        "target_index": int(target["canonical_index"]),
        "snapshot_budgets": set(budgets),
        "checkpoints": [],
        "context_snapshots": {},
        "fit_call_count": 0,
        "fit_pair_count": 0,
        "context_count": 0,
        "pending_pair": None,
        "latest_pair": None,
    }
    interval_audit = _new_interval_audit()
    interval_backend = (
        _temporary_calibration_interval_backend(interval_audit)
        if policy == EXACT_POLICY
        else nullcontext()
    )
    with _temporary_exact_registration():
        with interval_backend, _temporary_trial_injection(capture):
            harness_result = _FROZEN_RUN_TRIAL(
                policy=policy,
                seed=int(seed),
                z=int(stratum),
                gamma=float(gamma),
                sim="osa",
                mode="latent",
                noise="fixed",
                traj=False,
                budget=int(maximum_budget),
                warmup=WARMUP,
                r_k=COHORT_SIZE,
                grid_n=GRID_N,
                empty_gate="pf",
                kap=1.0,
                protocol_scaffold="lhs_fixed",
            )
    probability_fallbacks = int(
        interval_audit[_INTERVAL_AUDIT_PROBABILITY_COUNT]
    )
    log_probability_fallbacks = int(
        interval_audit[_INTERVAL_AUDIT_LOG_PROBABILITY_COUNT]
    )
    if probability_fallbacks != log_probability_fallbacks:
        raise CalibrationCoreError(
            "ordinary/log narrow-interval fallback counts are not paired"
        )
    if policy != EXACT_POLICY and probability_fallbacks:
        raise CalibrationCoreError(
            "a non-cKG calibration path invoked the exact interval fallback"
        )
    interval_audit[_INTERVAL_AUDIT_PAIR_CHECK] = True
    if capture["pending_pair"] is not None:
        raise CalibrationCoreError("frozen harness ended on an incomplete endpoint fit pair")
    expected_contexts = (int(maximum_budget) - WARMUP) // COHORT_SIZE
    if int(capture["context_count"]) != expected_contexts:
        raise CalibrationCoreError("frozen harness produced the wrong number of Context checkpoints")
    if int(capture["fit_pair_count"]) != expected_contexts + 1:
        raise CalibrationCoreError("frozen harness produced the wrong number of fit pairs")
    latest = capture.get("latest_pair")
    if not isinstance(latest, Mapping) or int(latest["n"]) != int(maximum_budget):
        raise CalibrationCoreError("maximum-budget observations were not captured")
    history = np.asarray(latest["X"], dtype=float)
    observed_efficacy = np.asarray(latest["Yf"], dtype=float)
    observed_toxicity = np.asarray(latest["Yg"], dtype=float)
    if not np.array_equal(history, np.asarray(harness_result["allocation_history"], dtype=float)):
        raise CalibrationCoreError("captured history differs from frozen harness output")
    above = np.asarray(
        [surface["tox"](float(d[0]), float(d[1])) > float(surface["gd"]) for d in history],
        dtype=bool,
    )
    true_eff, true_tox = _panel_truth(surface, Xset)

    identity = {
        "schema_version": SCHEMA_VERSION,
        "design_id": DESIGN_ID,
        "policy": str(policy),
        "seed": int(seed),
        "sim": "osa",
        "stratum": int(stratum),
        "gamma": float(gamma),
        "mode": "latent",
        "noise": "fixed_assumed_variance",
        "protocol_scaffold": "lhs_fixed",
        "warmup": WARMUP,
        "r_k": COHORT_SIZE,
        "grid_n": GRID_N,
        "empty_gate": "pf",
        "maximum_budget": int(maximum_budget),
        "snapshot_budgets": list(budgets),
    }
    replayed: list[tuple[dict[str, Any], Any, Any, Any, Any]] = []
    for budget in budgets:
        fitted_snapshot = _posterior_state(
            history,
            observed_efficacy,
            observed_toxicity,
            budget,
            torch.tensor(Xset, dtype=torch.double),
            surface,
            float(gamma),
            assumed_tox_variance,
        )
        replayed.append(fitted_snapshot)

    checkpoints = [dict(item) for item in capture["checkpoints"]]
    maximum_state = replayed[-1][0]
    target_index = int(target["canonical_index"])
    checkpoints.append(
        {
            "n": int(maximum_budget),
            "target_toxicity_mean": float(maximum_state["toxicity_posterior_mean"][target_index]),
            "target_toxicity_latent_sd": float(
                maximum_state["toxicity_posterior_latent_sd"][target_index]
            ),
            "target_stable_z": float(maximum_state["toxicity_stable_z"][target_index]),
            "target_feasibility_probability": float(
                maximum_state["toxicity_feasibility_probability"][target_index]
            ),
            "target_admitted": bool(maximum_state["gate_mask"][target_index]),
            "gate_count": int(sum(maximum_state["gate_mask"])),
            "gate_empty": not bool(any(maximum_state["gate_mask"])),
            "most_feasible_index": int(
                np.argmax(np.asarray(maximum_state["toxicity_stable_z"], dtype=float))
            ),
            "fitted_toxicity_noise_variance": float(
                maximum_state["fitted_toxicity_gp"]["observation_noise_variance"]
            ),
        }
    )
    expected_ns = list(range(WARMUP, int(maximum_budget) + 1, COHORT_SIZE))
    if [int(item["n"]) for item in checkpoints] != expected_ns:
        raise CalibrationCoreError("captured target gate history is incomplete")
    empty_gate_action_checks = 0
    empty_gate_action_differences = 0
    for item in checkpoints[:-1]:
        if not bool(item["gate_empty"]):
            continue
        empty_gate_action_checks += 1
        n = int(item["n"])
        expected_dose = Xset[int(item["most_feasible_index"])]
        assigned = history[n : n + COHORT_SIZE]
        empty_gate_action_differences += int(
            assigned.shape != (COHORT_SIZE, 2)
            or not np.all(assigned == expected_dose[None, :])
        )
    if empty_gate_action_differences:
        raise CalibrationCoreError(
            "an empty gate did not assign the next cohort at argmax stable-z"
        )

    innovation_audit = _replay_outcome_innovations(
        int(seed),
        int(maximum_budget),
        history,
        observed_efficacy,
        observed_toxicity,
        surface,
    )

    snapshots = [
        _finalize_snapshot(
            fitted_snapshot[0],
            record_identity=identity,
            surface=surface,
            Xset=Xset,
            true_eff=true_eff,
            true_tox=true_tox,
            target=target,
            history=history,
            above=above,
            checkpoints=checkpoints,
            context_state=capture["context_snapshots"].get(
                int(fitted_snapshot[0]["budget"])
            ),
            harness_result=harness_result,
            efficacy_model=fitted_snapshot[1],
            toxicity_model=fitted_snapshot[3],
        )
        for fitted_snapshot in replayed
    ]
    record = {
        **identity,
        "truth_eff_noise_sd": float(surface["sf"]),
        "truth_tox_noise_sd": float(surface["sg"]),
        "assumed_eff_noise_sd": float(surface["sf"]),
        "assumed_tox_noise_sd": float(surface["sg"]) * factor,
        "assumed_tox_noise_sd_factor": factor,
        "assumed_tox_noise_variance_factor": factor**2,
        "toxicity_threshold": float(surface["gd"]),
        "allocation_history": history.astype(float).tolist(),
        "observed_efficacy": observed_efficacy.astype(float).tolist(),
        "observed_toxicity": observed_toxicity.astype(float).tolist(),
        "above_boundary_labels": above.astype(bool).tolist(),
        "outcome_innovation_stream": innovation_audit,
        "true_panel_target": target,
        "checkpoints": checkpoints,
        "snapshots": snapshots,
        "audit": {
            "status": "checked",
            "frozen_harness_reused": True,
            "truth_noise_unchanged": True,
            "toxicity_fit_variance_only_perturbation": True,
            "fit_call_count": int(capture["fit_call_count"]),
            "fit_pair_count": int(capture["fit_pair_count"]),
            "allocation_context_count": int(capture["context_count"]),
            "maximum_terminal_replay_checked": True,
            "allocation_time_snapshot_context_replay_count": int(
                sum(
                    int(fitted_snapshot[0]["budget"])
                    in capture["context_snapshots"]
                    for fitted_snapshot in replayed
                )
            ),
            "outcome_innovation_stream_replay_checked": True,
            "empty_gate_action_checks": empty_gate_action_checks,
            "empty_gate_action_difference_count": empty_gate_action_differences,
            **interval_audit,
        },
    }
    validate_path_record(record)
    return record


def snapshot_by_budget(record: Mapping[str, Any], budget: int) -> Mapping[str, Any]:
    matches = [item for item in record.get("snapshots", []) if int(item["budget"]) == int(budget)]
    if len(matches) != 1:
        raise CalibrationCoreError(f"record has {len(matches)} snapshots at budget {budget}")
    return matches[0]


def flatten_snapshot(record: Mapping[str, Any], budget: int) -> dict[str, Any]:
    """Return one analysis-ready logical row without dropping the raw vectors."""
    snapshot = snapshot_by_budget(record, budget)
    recommendation = snapshot["recommendation"]
    target_gate = snapshot["target_gate"]
    calibration = snapshot["posterior_calibration"]
    gate = snapshot["gate_diagnostics"]
    row = {
        key: record[key]
        for key in (
            "schema_version",
            "design_id",
            "policy",
            "seed",
            "sim",
            "stratum",
            "gamma",
            "mode",
            "protocol_scaffold",
            "warmup",
            "r_k",
            "grid_n",
            "truth_eff_noise_sd",
            "truth_tox_noise_sd",
            "assumed_eff_noise_sd",
            "assumed_tox_noise_sd",
            "assumed_tox_noise_sd_factor",
            "assumed_tox_noise_variance_factor",
        )
    }
    row.update(snapshot["outcomes"])
    row.update(
        {
            "budget": int(budget),
            "n_enrolled": int(snapshot["n_enrolled"]),
            "rec_index": int(recommendation["index"]),
            "rec_d1": float(recommendation["dose"][0]),
            "rec_d2": float(recommendation["dose"][1]),
            "rec_true_eff": float(recommendation["true_efficacy"]),
            "rec_true_tox": float(recommendation["true_toxicity"]),
            "rec_unsafe": int(recommendation["unsafe"]),
            "panel_correct_selection": int(recommendation["panel_correct_selection"]),
            "grid_unit_distance_from_target": float(
                recommendation["grid_unit_distance_from_target"]
            ),
            "simple_regret_if_true_feasible": recommendation[
                "simple_regret_if_true_feasible"
            ],
            **target_gate,
            **calibration,
            **gate,
            "allocation_history": snapshot["frozen_run_trial_common"]["allocation_history"],
            "frozen_run_trial_common": snapshot["frozen_run_trial_common"],
        }
    )
    return row


def validate_path_record(record: Mapping[str, Any]) -> None:
    """Reject malformed or internally inconsistent serialized path records."""
    required = {
        "schema_version",
        "design_id",
        "policy",
        "seed",
        "stratum",
        "gamma",
        "maximum_budget",
        "snapshot_budgets",
        "truth_tox_noise_sd",
        "assumed_tox_noise_sd",
        "assumed_tox_noise_sd_factor",
        "allocation_history",
        "observed_efficacy",
        "observed_toxicity",
        "above_boundary_labels",
        "outcome_innovation_stream",
        "true_panel_target",
        "checkpoints",
        "snapshots",
        "audit",
    }
    missing = sorted(required - set(record))
    if missing:
        raise CalibrationCoreError(f"path record misses required fields: {missing}")
    if record["schema_version"] != SCHEMA_VERSION or record["design_id"] != DESIGN_ID:
        raise CalibrationCoreError("path record carries the wrong schema identity")
    maximum = int(record["maximum_budget"])
    for key in ("allocation_history", "observed_efficacy", "observed_toxicity", "above_boundary_labels"):
        if len(record[key]) != maximum:
            raise CalibrationCoreError(f"{key} length differs from maximum budget")
    if np.asarray(record["allocation_history"], dtype=float).shape != (maximum, 2):
        raise CalibrationCoreError("allocation_history does not have shape (maximum_budget, 2)")
    factor = float(record["assumed_tox_noise_sd_factor"])
    if not np.isclose(
        float(record["assumed_tox_noise_sd"]),
        float(record["truth_tox_noise_sd"]) * factor,
        rtol=0.0,
        atol=1e-12,
    ):
        raise CalibrationCoreError("assumed toxicity-noise SD does not equal truth times factor")
    expected_ns = list(range(WARMUP, maximum + 1, COHORT_SIZE))
    if [int(item["n"]) for item in record["checkpoints"]] != expected_ns:
        raise CalibrationCoreError("target checkpoints are not the complete cohort grid")
    budgets = [int(value) for value in record["snapshot_budgets"]]
    if [int(item["budget"]) for item in record["snapshots"]] != budgets:
        raise CalibrationCoreError("snapshot list does not match snapshot_budgets")
    for snapshot in record["snapshots"]:
        for key in (
            "efficacy_posterior_mean",
            "efficacy_posterior_latent_sd",
            "toxicity_posterior_mean",
            "toxicity_posterior_latent_sd",
            "toxicity_stable_z",
            "toxicity_feasibility_probability",
            "gate_mask",
        ):
            if len(snapshot[key]) != GRID_N**2:
                raise CalibrationCoreError(f"snapshot {snapshot['budget']} field {key} is not a 25-vector")
        mu_g = np.asarray(snapshot["toxicity_posterior_mean"], dtype=float)
        sd_g = np.asarray(snapshot["toxicity_posterior_latent_sd"], dtype=float)
        stable_z = np.asarray(snapshot["toxicity_stable_z"], dtype=float)
        expected_z = (float(record["toxicity_threshold"]) - mu_g) / sd_g
        if not np.allclose(stable_z, expected_z, rtol=1e-12, atol=1e-12):
            raise CalibrationCoreError("serialized snapshot stable-z vector is inconsistent")
        expected_gate = stable_z > float(snapshot["gate_quantile"])
        if not np.array_equal(expected_gate, np.asarray(snapshot["gate_mask"], dtype=bool)):
            raise CalibrationCoreError("serialized snapshot gate mask is inconsistent")
        expected_variance = float(record["assumed_tox_noise_sd"]) ** 2
        if not np.isclose(
            float(snapshot["fitted_toxicity_gp"]["observation_noise_variance"]),
            expected_variance,
            rtol=0.0,
            atol=2e-5,
        ):
            raise CalibrationCoreError("snapshot toxicity likelihood did not use assumed variance")
        if snapshot["terminal_rule_audit"]["status"] != "checked":
            raise CalibrationCoreError("snapshot terminal-rule audit is not checked")
    if record["audit"].get("status") != "checked":
        raise CalibrationCoreError("path-level audit is not checked")
    audit = record["audit"]
    probability_fallbacks = int(
        audit.get(_INTERVAL_AUDIT_PROBABILITY_COUNT, -1)
    )
    log_probability_fallbacks = int(
        audit.get(_INTERVAL_AUDIT_LOG_PROBABILITY_COUNT, -1)
    )
    if probability_fallbacks < 0 or log_probability_fallbacks < 0:
        raise CalibrationCoreError("narrow-interval fallback count is invalid")
    if probability_fallbacks != log_probability_fallbacks:
        raise CalibrationCoreError(
            "ordinary/log narrow-interval fallback counts are not paired"
        )
    max_bound = float(audit.get(_INTERVAL_AUDIT_MAX_BOUND, np.inf))
    cap = float(audit.get(_INTERVAL_AUDIT_CAP, np.nan))
    if (
        not np.isfinite(max_bound)
        or max_bound < 0.0
        or not np.isclose(
            cap,
            _decimal_upper_float(_NARROW_INTERVAL_ANALYTIC_LOG_ERROR_CAP),
            rtol=0.0,
            atol=0.0,
        )
        or max_bound > cap
    ):
        raise CalibrationCoreError("narrow-interval fallback error bound is invalid")
    if (probability_fallbacks == 0) != (max_bound == 0.0):
        raise CalibrationCoreError(
            "narrow-interval fallback count and maximum bound disagree"
        )
    if not bool(audit.get(_INTERVAL_AUDIT_PAIR_CHECK, False)):
        raise CalibrationCoreError("narrow-interval fallback pair audit did not pass")
    if record["policy"] != EXACT_POLICY and probability_fallbacks != 0:
        raise CalibrationCoreError(
            "a non-cKG path carries exact interval-fallback invocations"
        )
    innovation = record["outcome_innovation_stream"]
    if int(innovation.get("innovation_count_per_endpoint", -1)) != maximum:
        raise CalibrationCoreError("innovation-stream audit has the wrong length")
    for key in ("combined_sha256", "efficacy_sha256", "toxicity_sha256"):
        value = innovation.get(key)
        if not isinstance(value, str) or len(value) != 64:
            raise CalibrationCoreError("innovation-stream audit has an invalid hash")
    if int(record["audit"].get("empty_gate_action_difference_count", -1)) != 0:
        raise CalibrationCoreError("empty-gate action audit did not pass")


__all__ = [
    "CalibrationCoreError",
    "DESIGN_ID",
    "EXACT_POLICY",
    "PATH_SCHEMA_VERSION",
    "PATH_SORT_FIELDS",
    "POLICIES",
    "PRODUCTION_FACTORS",
    "PRODUCTION_GAMMAS",
    "PRODUCTION_SNAPSHOT_BUDGETS",
    "cleanup_worker",
    "flatten_snapshot",
    "initialize_worker",
    "run_calibration_path",
    "snapshot_by_budget",
    "validate_path_record",
]
